name: Pull request update

on:
    push:
        branches:
            - main

jobs:
    autoupdate:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        - name: Update ALL THE PRS!
          uses: castastrophe/actions-pr-auto-update@02e7423a75162eea2328c805520f99f22a81b662  # v1.0.0
          with:
                # defaults to github.token
                token: ${{ secrets.GITHUB_TOKEN }}
                # Optional: include a limit to the number of PRs to update (default is 100)
                limit: 10
                # Optional: set this to true if you want to include draft PRs in those to be updated
                include_drafts: true
                # Optional: include a list of labels which, if present, will prevent the PR from being updated; these are comma-separated.
                exclude_labels: "do not update,skip update"
                # Optional: include a list of labels, at least one of which are required to be present for the PR to be updated; these are comma-separated.
                include_labels: "update,update me"
